### ISSUE TITLE
Threads - need more info!

### ISSUE THREAD

**Issue by nikmachines** [c0pperdragon/EV3Basic#15]
Could you please give good example of how to use the power of threads in EV3 Basic? - it would be nice to have explanation about Thread.CreateMutex (), Thread.Lock (mutex),Thread.Unlock (mutex), Thread.Yield ().

**Comment by c0pperdragon** [comment]
I have made a new and better example for the use of threads:

https://github.com/c0pperdragon/EV3Basic/blob/master/Examples/Threads.sb

**Comment by nikmachines** [comment]
Thanks a lot! It's almost clear for me now :) Could you please tell some words about Thread.Yield ()? What's the practical use of this command?

**Comment by c0pperdragon** [comment]
This command is only useful in extremely rare occasions. Imagine you have a thread that needs to do some heavy computation that takes a long time. At the same time you have a thread that does some time-critical actions, like controlling a motor. Normally each threads would get the CPU to do a part of its work and then the CPU will be passed to the other thread. If these timeslices are too coarsly grained so that the time-critical thread has too long pauses before it can continue, the motor control may be not precise enough.  To mitigate this issue, the CPU-intensive thread may voluntaringly give up control of the CPU in very short intervals during its computation using Thread.Yield(). This allows the other thread to have shorter check intervals.
