### ISSUE TITLE
Beginner's confusion?

### ISSUE THREAD

**Issue by joserbngithub** [c0pperdragon/EV3Basic#26]
Dear Reinhard,

 Thanks a lot for developing the EV3 basic library!! I'm aiming to teach coding to my son using the mindstorms setup but I have an issue which you might be able to help me with.

 I'm a seasoned computer user and got small basic running. However, I installed the EV3 basic library and can see it under windows> small basic > Lib, I follwoed the advice to enable .NET under windows 10 but still can't get small basic to acknowledge the EV3 library. Any suggestions for getting the EV3 extension running?

 All help will be greatly appreciated!

Thanks,
Jose'

**Comment by c0pperdragon** [comment]
Maybe you are using the Small Basic version that is available on the Microsoft Store? This seems plausible because you are using Windows 10. This version is not compatible with any extensions as it is installed into a high-security area of the operating system that can not be accessed to install the necessary files.

Try to get the Small Basic 1.2 installer from the offical Small Basic website:  
https://smallbasic-publicwebsite.azurewebsites.net/

**Comment by joserbngithub** [comment]
Thanks!

Yes, that was the case. An ev3 basic user from Australia suggested a similar thing and last night I got the mind storms running :)

My son already wants to know how to make the robot move using the keyboard arrows, which will be his first project ;)

Thanks again for implementing the ev3 extension!!

Cheers,
José

---
José Brandão
Skype joserbn

________________________________
