### ISSUE TITLE
Need Program.Delay in loops for motors to work properly?

### ISSUE THREAD

**Issue by RudkevichD** [c0pperdragon/EV3Basic#29]
Hello! You make an awesome job with EV3Basic! Thank you!
I notice, if I use Motor.Start in loops with changing speed, rotations become jerky.
For example. This program suppose to change speeds of two big motors smoothly by sinusoidal law:
```
st = EV3.Time
While "True"
	t = EV3.Time - st
	v = 60 + 40 * Math.Sin(t/1000)
	Motor.Start("B",-v)
	Motor.Start("C",-v)
EndWhile
```
Robot moves are very jerky. Not smooth.
But if I put `Program.Delay(50) `inside loop, everything become smooth and good. Looks like Brick needs some processor resources to control motors properly?

I tried to make an equal program in Mindstorms software and it works smooth without need of delay or smth.
So I wonder, why I encounter such problems in basic programs and not in programs created in standard graphical language of EV3 Mindstorms? Did this means, the basic programs tend to be slower (because of need of Program.Delay) or in contrary, basic programs have bigger priority in Brick operation system and I need to manage CPU load?

**Comment by c0pperdragon** [comment]
I am not sure what the difference is. Maybe the lego software inserts a small delay after changing motor speed for exactly that reason. In my experience having smooth running motors is not a matter of CPU load. Probably firing motor commands in so close succession is the real problem. If it works with a small delay, keep to this.

**Comment by RudkevichD** [comment]
Ah. So, Lego software inserts delay after motor speed changes? Interesting! Do you know the exact value of this delay? Looks like inserting delays in basic is the legitimate method for managing motors, than. Will keep it in mind. Thank you!

**Comment by c0pperdragon** [comment]
Maybe I have not made myself clear enough. It is only a wild guess on my side that the lego software inserts a delay. But you could try to test this hypothesis by doing many motor actions in a tight loop and measure the time it takes. Compare this to how long it takes EV3 Basic to do the same, and you could get an idea what is going on in each case.

**Comment by RudkevichD** [comment]
I made an experiment. Remade the loop in the example above to make 10000 ticks and check the time. The results are:
10k ticks in basic program changing speed on two motors on every tick: 7.3 seconds
10k ticks in EV3 software changing speed on two motors on every tick: 8.3 seconds
But when basic program is running, motors movement is jerky (especially on low speeds)
To remove jerkiness, need at least 15 milliseconds of delay inside the loop. But with this delay, 10k ticks will take more than 150 seconds to complete!
Looks like the problem is not in delays, but the function Motor.Start called too often. Looks like Brick can handle something around 60 motor instructions per second without issues (50 or 60 Hz make sense). I think Lego software handles this automatically (just drops all excess instructions beyond 50 per second).
I made more advanced program in basic: instead of calling Motor.Start, I made а Sub UpdateMotors. This sub changes motors speed only if time passed, from last changes is more than 15 milliseconds.
It works perfectly. It takes only 2.8 seconds to complete 10k ticks and no jerkiness at all.
I think this is the right way EV3Basic programs must handle motors: make sure not to change motor speeds more than 50 times per seconds. Its harder than standard Lego way, but potentially its waaay faster.

**Comment by ghost** [comment]
RudkevichD, I think your analysis is spot on.

My understanding is that the Lego blocks update at maybe 100Hz maybe less (I remember this info somewhere in the EV3-G documentation about the gyro).

We encountered this "jerkiness" when using MakeCode Mindstorms and trying to do a ramp. The jerkiness of the ramp was probably caused by the same mechanism.

Thanks for posting your workaround with the Sub UpdateMotors. My FLL team is planning on using EV3 Basic for their competition this season and they are just now getting to the programming of their various "move" and "turn" subroutines.

This will save a lot of headaches and also be a good lesson for them on checking the "Issues" pages on Github.

And c0pperdragon, thanks for your work. This is exactly what we needed for my team this year to move them into real programming languages.

**Comment by RudkevichD** [comment]
Hey, c0pperdragon, I have another hypotheses!
I was looking through repository to find clues on the subject, and found something here: https://github.com/c0pperdragon/EV3Basic/blob/master/EV3BasicCompiler/Resources/Motor.txt 
in subcall MOTOR.START 
Here you use
OUTPUT_TIME_SPEED layer nos spd 0 2147483647 0 0
to start motors. If I understand correctly, this line starts scheduled motor operation with 0 seconds for ramping up, infinite seconds for constant motion and 0 seconds for ramping down period.
Isn’t this command will be more suitable:
opOutput_Speed (LAYER, NOS, SPEED)  
(I found it in the Lego documentation here: https://le-www-live-s.legocdn.com/sc/media/files/ev3-developer-kit/lego%20mindstorms%20ev3%20firmware%20developer%20kit-7be073548547d99f7df59ddfd57c0088.pdf)

Maybe opOutput_Time_Speed doesn’t supports multiple fast calls and is what causing jerkiness? Or maybe I just didn’t understand how the opOutput_Speed works… :)

**Comment by RudkevichD** [comment]
Yep.
I download project and made this changes just to test my hypotheses
In Motor.txt, in subcall MOTOR.START
instead of OUTPUT_TIME_SPEED layer nos spd 0 2147483647 0 0, I put this two lines:
    OUTPUT_SPEED layer nos spd
    OUTPUT_START layer nos

Also in Motor.cs in Motor.Start I put this:
                c.OP(0xA5);       // opOutput_Speed
                c.CONST(layer);
                c.CONST(nos);
                c.CONST(spd);
                EV3RemoteControler.DirectCommand(c, 0, 0);
                ByteCodeBuffer c2 = new ByteCodeBuffer();
                c2.OP(0xA5);       // opOutput_Speed
                c2.CONST(layer);
                c2.CONST(nos);
                EV3RemoteControler.DirectCommand(c2, 0, 0);

For testing I used this basic program:
m1:
t = EV3.Time
v = 2 + 97 * Math.Sin(t / 2000)
Motor.Start("A",-v)
Motor.Start("D",v)
Program.Delay(1)
Goto m1

With old EV3BasicCompiler.dll, motor motions were jerky on low speeds.
With new EV3BasicCompiler.dll with above changes, everything works smooth and fast. 
But Maybe I didn't see some underwater stones?

UPDATE:
I made an error in Motor.cs. Need to put
c2.OP(0xA6);       // opOutput_Start

But looks like this part didn't effect Compiler (used in desktop side execution, I presume)

**Comment by c0pperdragon** [comment]
Thank you for this investigation.
So it seems the OUTPUT_TIME_SPEED is the culprit in your use case. I tried to investigate why I have used this call in the first place. 
As it turns out, using OUTPUT_SPEED and OUTPUT_START works by itself, but there is something bad happening when used in conjunction with other motor commands. One main problem is that it is not possible to set the motor to some other drive mode while it is still running. For example Motor.StartPower has no effect after a Motor.Start without a Motor.Stop in between. And there  are propably other gliches as well. I guess this behavior was the main reason why I went for the other method. 

I don't think I should change the implementation of the Motor commands as it could introduce any number of incompatibilities for existing programs.
So you can either use your modifications for your purposes, or just live with the fact that you need to insert some delay between motor calls, to get it working smoothly.

**Comment by ghost** [comment]
I agree with you not to mess with it in the short term.

The work around with the time delay seems to work well enough.

Thank you for looking into it.

EV3 Small Basic certainly is a much better tool to use for FLL than some
other options.

**Comment by c0pperdragon** [comment]
I did a small experiment on this issue, and if you want to do a super-tight control loop to adjust the motor speed constantly, you can also use Motor.StartPower.

This progam just alternates the motor speed as fast as possible. Running absolutely smoothly:
start = EV3.Time
While "true"
  t = EV3.Time - start
  Motor.StartPower("A", 100 * Math.Sin(t/1000))  
endwhile

The problem with the Motor.Start (as probably also with the Motor.StartSteer, Motor.StartSync) call seems to be that it re-initializes the speed regulation algorithm. This leads to that jerky behaviour.
The Motor.StartPower on the other hand just changes the duty cycle of the PWM signal to the specified value.

So if you can implement your own speed regulation algorithm, you can have a super-smooth and super-responsive motor control.

**Comment by ghost** [comment]
Thank you. We'll try this out and then try to modify what's here.
