### ISSUE TITLE
Prevent brick from going to sleep

### ISSUE THREAD

**Issue by DanieleBenedettelli** [c0pperdragon/EV3Basic#34]
Hello.
Is there a way to prevent the brick from going to sleep when a program is running? Not sure if it's already done, or it needs a special keepalive command.
Thanks

**Comment by c0pperdragon** [comment]
I have not experimented with too much. I just disabled automatic switch off on my brick altogether. If I remember correctly this can be done with the on-brick settings menu.
This can of course lead to a completely drained battery if you forget to switch it off manually.

The behavior may be different when running the program directly on the brick or if remote-controlling it from the PC. In the second case, the brick is not even aware that there is some program running at all, so it will probably switch off after the given time. For programs running on the brick, this may be different. Not sure though, because it can lead to the exact same problem of draining the battery. 

As the EV3 is targeted primarily at children or teenagers, not switching things off is surely a very common thing.

**Comment by DanieleBenedettelli** [comment]
I will just set the option to never because it would be really bad for the
robot to shut down in the middle of a competition.

Thanks

Il giorno gio 20 feb 2020 alle ore 15:50 c0pperdragon <
notifications@github.com> ha scritto:
